# Generated by Django 4.1.1 on 2022-11-24 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrimeraApp', '0003_alter_cursos_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='imagen',
            field=models.FileField(upload_to='fotos'),
        ),
    ]
