# Generated by Django 4.1.1 on 2022-11-28 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrimeraApp', '0006_formulario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulario',
            name='curso',
        ),
        migrations.AddField(
            model_name='formulario',
            name='curso',
            field=models.ManyToManyField(to='PrimeraApp.cursos'),
        ),
    ]
